name: CI MSM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]
    steps:
      - name: Descarregar codi
        uses: actions/checkout@v4

      - name: Configurar PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Instal·lar dependències
        run: composer install

      - name: Executar tests amb informe JUnit
        run: ./vendor/bin/phpunit --log-junit resultats.xml

      - name: Pujar artefacte
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultats-MSM
          path: resultats.xml